#!/bin/sh
set -e
s=startuptime.txt
[ $# = 0 ] && set -- *.*  # default to all files with a dot
[ $# -gt 1 ] && multi=1 || multi=
for sample in "$@"; do
  vim --startuptime $s -c qa "$sample"
  run=$(awk '/\/after\/syntax\/css\.vim$/ {sum += $2} END {print sum}' "$s")
  rm $s
  echo "$run${multi:+\t$sample}"
  total="${total:-0} + ${run:-0}"
done
# if multi, show the sum total. otherwise, return true only if we had a run.
[ -n "$multi" ] && echo "$(echo "$total" |bc -ql)\t(total)" || [ -n "$run" ]
